### ISSUE TITLE
Incomplete building documentation

### ISSUE THREAD

**Issue by levicki** [daz3d/StudioFbxImporter#2]
@rbtwhiz 

README.md doesn't mention that you need Qt to build the importer, nor which version of Qt, nor whether you need shared or static libraries:

![image](https://user-images.githubusercontent.com/16415478/197402597-97a0a031-2c0f-4741-910d-d7d29cef928a.png)

From what I see in the latest Daz Studio Public Beta 4.21.0.5, the Qt version used is 4.8.7, but it is x64 and that is not provided on the Qt website, not to mention that any prebuilt binaries available there are built using ancient Visual Studio and MinGW compilers.

Finally, it is not clear that for FBX SDK path you need to set only `C:\Program Files\Autodesk\FBX\FBX SDK` and not `C:\Program Files\Autodesk\FBX\FBX SDK\2020.2.1` because `2020.2.1` will be automatically appended. For someone dealing with FBX SDK for the first time this isn't really intuitive and is worth mentioning in the README.

**Comment by rbtwhiz** [comment]
Qt files required to build the plugin for a given platform are distributed with the application, and/or the Daz Studio SDK. There are no additional requirements to download, configure, and/or build Qt itself - choosing to do so is beyond the scope of this project. The README has been updated to reflect this.

The README has also been updated to clarify the path expected by `FBX_SDK_INSTALL_DIR` and the significance of the `FBX_SDK_VERSION` and `FBX_SDK_VSTUDIO_VERSION` variables.

**Comment by levicki** [comment]
@rbtwhiz I see, thanks for clarifying.

Maybe you could change the CMake file to derive Qt path automatically from Daz SDK path then, given that the relevant Qt `.lib` files are indeed there?

**Comment by rbtwhiz** [comment]
[CMakeLists](https://github.com/daz3d/StudioFbxImporter/blob/main/CMakeLists.txt) uses [find_package](https://cmake.org/cmake/help/v3.4/command/find_package.html), which in turn uses the [FindQt4](https://cmake.org/cmake/help/v3.4/module/FindQt4.html) module, to locate Qt 4.8. That module sets several `QT_` prefixed variables based on the paths assigned [a few lines before](https://github.com/daz3d/StudioFbxImporter/blob/6bb9172dcc605d6ade1363e57946fc323d4154c2/CMakeLists.txt#L92) use of [find_package](https://github.com/daz3d/StudioFbxImporter/blob/6bb9172dcc605d6ade1363e57946fc323d4154c2/CMakeLists.txt#L102). Because the module does not find anything in a `<DAZ_SDK_DIR>/imports` directory (_we do not include the QML binaries that would be located within that directory in the DS SDK footprint, so we do not discretely set that path_), the value it assigns to the `QT_IMPORTS_DIR` variable reverts to the path on the machine that built the included Qt binaries.

The presence of the value has no impact on the building of this plugin (_or any other plugin built with the Daz Studio 4.5+ SDK_). It can be removed, but it is likely to return if/when configuration is changed (_e.g., to switch between FBX SDK versions_).

**Comment by levicki** [comment]
@rbtwhiz Thanks for clarification.
