### ISSUE TITLE
FBX Importer is broken and cannot import anything properly

### ISSUE THREAD

**Issue by levicki** [daz3d/StudioFbxImporter#3]
@rbtwhiz I am sure you guys are aware of this, but just in case you aren't, the FBX importer as it is (both the version distributed with Daz Studio 4.21.0.5 Public Beta and my custom compiled using FBX SDK 2020.2.1) are broken (i.e. can't import figures with rigging and animations).

For example trying to import this:

![image](https://user-images.githubusercontent.com/16415478/197403976-6e03eed0-ef5c-4a32-8dd6-9fb73b5490b1.png)

Results in this:

![image](https://user-images.githubusercontent.com/16415478/197404039-3103ae55-7458-491a-880d-5ca818a82573.png)

Full pre-import report says:
```
Rigging: Pre/Post rotation mismatch: BoneRoot
Rigging: Bone chain type incorrect - Limb Node: BoneRoot
Rigging: Non-uniform scale: CC_Base_Hip
Rigging: Non-uniform scale: CC_Base_Pelvis
Rigging: Non-uniform scale: CC_Base_L_Thigh
Rigging: Non-uniform scale: CC_Base_L_Foot
Rigging: Non-uniform scale: CC_Base_L_ToeBaseShareBone
Rigging: Non-uniform scale: CC_Base_L_ToeBase
Rigging: Non-uniform scale: CC_Base_L_PinkyToe1
Rigging: Non-uniform scale: CC_Base_L_RingToe1
Rigging: Non-uniform scale: CC_Base_L_MidToe1
Rigging: Non-uniform scale: CC_Base_L_IndexToe1
Rigging: Non-uniform scale: CC_Base_L_BigToe1
Rigging: Non-uniform scale: CC_Base_L_CalfTwist01
Rigging: Non-uniform scale: CC_Base_L_KneeShareBone
Rigging: Non-uniform scale: CC_Base_L_ThighTwist02
Rigging: Non-uniform scale: CC_Base_R_Thigh
Rigging: Non-uniform scale: CC_Base_R_Calf
Rigging: Non-uniform scale: CC_Base_R_KneeShareBone
Rigging: Non-uniform scale: CC_Base_R_Foot
Rigging: Non-uniform scale: CC_Base_R_ToeBase
Rigging: Non-uniform scale: CC_Base_R_BigToe1
Rigging: Non-uniform scale: CC_Base_R_PinkyToe1
Rigging: Non-uniform scale: CC_Base_R_RingToe1
Rigging: Non-uniform scale: CC_Base_R_IndexToe1
Rigging: Non-uniform scale: CC_Base_R_MidToe1
Rigging: Non-uniform scale: CC_Base_R_ToeBaseShareBone
Rigging: Non-uniform scale: CC_Base_R_CalfTwist01
Rigging: Non-uniform scale: CC_Base_R_CalfTwist02
Rigging: Non-uniform scale: CC_Base_R_ThighTwist01
Rigging: Non-uniform scale: CC_Base_R_ThighTwist02
Rigging: Non-uniform scale: CC_Base_Waist
Rigging: Non-uniform scale: CC_Base_Spine02
Rigging: Non-uniform scale: CC_Base_NeckTwist01
Rigging: Non-uniform scale: CC_Base_NeckTwist02
Rigging: Non-uniform scale: CC_Base_JawRoot
Rigging: Non-uniform scale: CC_Base_Tongue01
Rigging: Non-uniform scale: CC_Base_Tongue02
Rigging: Non-uniform scale: CC_Base_Tongue03
Rigging: Non-uniform scale: CC_Base_Teeth02
Rigging: Non-uniform scale: CC_Base_UpperJaw
Rigging: Non-uniform scale: CC_Base_Teeth01
Rigging: Non-uniform scale: CC_Base_L_Clavicle
Rigging: Non-uniform scale: CC_Base_L_Upperarm
Rigging: Non-uniform scale: CC_Base_L_Forearm
Rigging: Non-uniform scale: CC_Base_L_ForearmTwist01
Rigging: Non-uniform scale: CC_Base_L_ElbowShareBone
Rigging: Non-uniform scale: CC_Base_L_Hand
Rigging: Non-uniform scale: CC_Base_L_Pinky1
Rigging: Non-uniform scale: CC_Base_L_Pinky2
Rigging: Non-uniform scale: CC_Base_L_Pinky3
Rigging: Non-uniform scale: CC_Base_L_Ring1
Rigging: Non-uniform scale: CC_Base_L_Ring2
Rigging: Non-uniform scale: CC_Base_L_Ring3
Rigging: Non-uniform scale: CC_Base_L_Mid1
Rigging: Non-uniform scale: CC_Base_L_Mid2
Rigging: Non-uniform scale: CC_Base_L_Mid3
Rigging: Non-uniform scale: CC_Base_L_Index1
Rigging: Non-uniform scale: CC_Base_L_Index2
Rigging: Non-uniform scale: CC_Base_L_Index3
Rigging: Non-uniform scale: CC_Base_L_Thumb1
Rigging: Non-uniform scale: CC_Base_L_Thumb2
Rigging: Non-uniform scale: CC_Base_L_Thumb3
Rigging: Non-uniform scale: CC_Base_L_UpperarmTwist01
Rigging: Non-uniform scale: CC_Base_L_UpperarmTwist02
Rigging: Non-uniform scale: CC_Base_L_Breast
Rigging: Non-uniform scale: CC_Base_R_Breast
Rigging: Non-uniform scale: CC_Base_R_Clavicle
Rigging: Non-uniform scale: CC_Base_R_Upperarm
Rigging: Non-uniform scale: CC_Base_R_Forearm
Rigging: Non-uniform scale: CC_Base_R_ElbowShareBone
Rigging: Non-uniform scale: CC_Base_R_Hand
Rigging: Non-uniform scale: CC_Base_R_Ring1
Rigging: Non-uniform scale: CC_Base_R_Ring3
Rigging: Non-uniform scale: CC_Base_R_Mid1
Rigging: Non-uniform scale: CC_Base_R_Mid2
Rigging: Non-uniform scale: CC_Base_R_Mid3
Rigging: Non-uniform scale: CC_Base_R_Thumb1
Rigging: Non-uniform scale: CC_Base_R_Thumb2
Rigging: Non-uniform scale: CC_Base_R_Thumb3
Rigging: Non-uniform scale: CC_Base_R_Index1
Rigging: Non-uniform scale: CC_Base_R_Index2
Rigging: Non-uniform scale: CC_Base_R_Index3
Rigging: Non-uniform scale: CC_Base_R_Pinky1
Rigging: Non-uniform scale: CC_Base_R_Pinky2
Rigging: Non-uniform scale: CC_Base_R_Pinky3
Rigging: Non-uniform scale: CC_Base_R_UpperarmTwist01
```

The worst part is that you cannot even discard rigging and at least load the figure with textures so you can re-rig it in Daz Studio.

This is really atrocious level of support for the most popular file format and it really should be given some priority.

**Comment by rbtwhiz** [comment]
The "Pre-Import Report" lists occurrences that the plugin cannot, in its current form, handle. It is by no means an exhaustive list, but it has been made considerably more verbose in recent versions - in order to help isolate/highlight where the problems/incompatibilities are. Some of these occurrences may ultimately be addressable as the plugin evolves, and others may require modification of the content in the source application.

While FBX is a popular format, the data contained within one is not universal across all applications that produce and/or consume it - even _if_ a subset of the data happens to be agreed upon, there is no guarantee that _all_ of it will be. A feature/configuration/concept supported in one application may not exist, or may be represented in a different/incompatible way, in another.

This is not a matter of the plugin being "broken" (_it can "round-trip" a significant amount of data exported with the Daz Studio FBX Exporter_), so much as a matter of incompatibilities between the data in a given file and the rules around the concept of a skeleton/figure in Daz Studio. Further, the transformation model implemented in one application may not be representable as such in another. For example, even FBX/Maya and 3ds Max [do not entirely agree](https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_nodes_and_scene_graph_fbx_nodes_computing_transformation_matrix_html)... and Daz Studio differs from both.

The rotations on the `BoneRoot` node are [incompatible](https://github.com/daz3d/StudioFbxImporter/blob/6bb9172dcc605d6ade1363e57946fc323d4154c2/FBX%20Importer/DzFbxImporter.cpp#L1451) with the transformation model employed by Daz Studio - joint pre-rotation (_e.g., Maya: Joint > Joint Orient_) and post-rotation (_e.g., Maya: Transform Attributes > Rotate Axis_) values must be the quaternion inverse (_not inverse Euler angles_) of each other.

The hierarchy of FbxSkeleton nodes in this file is incompatible with the concept of a skeleton/figure in Daz Studio. In the Daz Studio model, there is a single root node (_a DzSkeleton - FbxSkeleton::eRoot_) and a hierarchy of DzBone instances (_FbxSkeleton::eLimbNode_).

The scaling applied to several nodes in this file is non-uniform (_not the same on all axis_), and [cannot be represented](https://github.com/daz3d/StudioFbxImporter/blob/6bb9172dcc605d6ade1363e57946fc323d4154c2/FBX%20Importer/DzFbxImporter.cpp#L1458) by the transformation model employed by Daz Studio.

If you would like to request a feature (_such as the ability to exclude rigging/binding information_), please do so in a separate issue.

While passion about the project is appreciated, it should be communicated in a constructive manner.

**Comment by levicki** [comment]
@rbtwhiz 

> While passion about the project is appreciated, it should be communicated in a constructive manner.

Please accept my apologies if what I wrote was offensive in any way. Wording what amounts to criticism in a constructive manner is a hard skill to master and apparently I still struggle with it.

> While FBX is a popular format, the data contained within one is not universal across all applications that produce and/or consume it - even if a subset of the data happens to be agreed upon, there is no guarantee that all of it will be. A feature/configuration/concept supported in one application may not exist, or may be represented in a different/incompatible way, in another.

I am fully aware of this, and I did not expect FBX importer to preserve Maya animation and rigging (which may be incompatible), nor any other format features that do not exist or cannot be represented in Daz Studio.

> Further, the transformation model implemented in one application may not be representable as such in another. For example, even FBX/Maya and 3ds Max [do not entirely agree](https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_nodes_and_scene_graph_fbx_nodes_computing_transformation_matrix_html)... and Daz Studio differs from both.

My takeaway from that link is:

_The FBX importers and exporters for 3ds Max automatically convert transformation matrices to and from 3ds Max._

Are you saying such conversion is impossible with Daz FBX importer or it is just not implemented?

The reason I used the word "broken" is that FBX importer seems incapable of importing even the base 3D mesh and (PBR) materials. I have searched Daz forums for information on how to import FBX to Daz Studio and all I found was:

 - Use Carrara because Carrara somehow can handle what Daz Studio FBX importer cannot (I have not verified this claim).
 - Import `.fbx` into Poser Pro 11 and export as `.cr2` then import that in Daz Studio (supposedly this discards rigging which is problematic).
 - Use Blender.

Each of those workarounds require either owning the license for the corresponding application or at the minimum learning their specific workflows and features when all you needed was to import a model into an application you already know how to use.

Most models available for purchase from professional 3D artists are made either in Maya or 3DS Max. Sometimes they provide also an `.obj` file, but materials going with that are usually exported in a very basic fashion (diffuse and normals), while FBX has PBR materials which Daz Studio supports at least to some extent.

Any improvements to FBX importer would thus be most welcome, and I can certainly create a separate issue (i.e. a feature request) if you think any such improvements could be made.

What I would like to see is:

1. The ability to discard animation and rigging.
2. The ability to select what to import if there is more than a single object/figure in the file.
3. Import of base object/figure geometry along with PBR textures (and any necessary adjustments to tie them in with Iray PBR shader).

Please let me know if I should create a separate issue for each of those and whether they are feasible or not.
